// src/utils/formSchema.ts
import { z } from 'zod';

export const formSchema = z.object({
  clientInfo: z.object({
    // fullName: z.string(),
    // phoneNumber: z.string(),
    // address: z.string(),
    clientCategory: z.enum(['farmer', 'distributor', 'retailer', 'partner', 'individualBuyer']).optional(),
    clientTier: z.enum(['standard', 'premium', 'enterprise']).optional(),
    accountManager: z.string().optional(),
    clientId: z.string(),
    updatedBy: z.string(),
    fullName: z.string().min(1, { message: 'form.fullNameRequired' }),
    phoneNumber: z.string().regex(/^\+?[1-9]\d{1,14}$/, { message: 'form.phoneNumberInvalid' }),
    email: z.string().email({ message: 'form.emailInvalid' }).optional().or(z.literal('')),
    gender: z.enum(['male', 'female', 'other', 'preferNotToSay']).optional(),
    address: z.string().min(1, { message: 'form.addressRequired' }),
    // clientCategory: z.enum(['farmer', 'distributor', 'retailer', 'partner', 'individualBuyer']).optional(),
    dateOfRegistration: z.string().optional(),
    referredBy: z.string().optional(),
    preferredContactMethod: z.enum(['sms', 'call', 'email', 'whatsapp']).optional(),
    businessName: z.string().optional(),
    taxId: z.string().optional(),
    loyaltyProgram: z.boolean().optional(),
    // clientTier: z.enum(['standard', 'premium', 'enterprise']).optional(),
    // accountManager: z.string().optional(),
  }),
  orderDetails: z.array(
    z.object({
      orderCategory: z.enum(['retail', 'wholesale', 'export']).optional(),
      productName: z.string().min(1, { message: 'form.productNameRequired' }),
      sku: z.string().optional(),
      unitType: z.enum(['liters', 'kilograms', 'bottles', 'bags']).optional(),
      quantity: z.number().min(1, { message: 'form.quantityRequired' }),
      unitPrice: z.number().min(0, { message: 'form.unitPriceRequired' }),
      discount: z.number().min(0).max(100).optional(),
      notes: z.string().optional(),
      orderUrgency: z.enum(['standard', 'urgent']).optional(),
      packagingPreference: z.enum(['standard', 'custom']).optional(),
      paymentSchedule: z.enum(['fullPayment', 'installments']).optional(),
    })
  ).min(1, { message: 'form.orderDetailsRequired' }),
  dispatch: z.array(
    z.object({
      product: z.string().min(1, { message: 'form.productRequired' }),
      quantityDispatched: z.number().min(1, { message: 'form.quantityDispatchedRequired' }),
      transportMethod: z.enum(['truck', 'motorcycle', 'onFoot', 'thirdPartyCourier']).optional(),
      dispatchStatus: z.enum(['scheduled', 'inTransit', 'delivered', 'delayed']).optional(),
      dispatchDate: z.string().optional(),
      trackingReference: z.string().optional(),
      dispatchNotes: z.string().optional(),
      driverContact: z.string().optional(),
      warehouseLocation: z.enum(['kigali', 'kayonza', 'musanze']).optional(),
      blockchainHash: z.string().optional(),
    })
  ).optional(),
  salesOps: z.object({
    salesRepresentative: z.string().optional(),
    paymentStatus: z.enum(['pending', 'partial', 'paid']).optional(),
    paymentMethod: z.enum(['cashOnDelivery', 'mPesa', 'bankTransfer', 'credit']).optional(),
    paymentReceived: z.number().min(0).optional(),
    paymentReceipt: z.any().nullable().optional(),
    deliveryStatus: z.enum(['processing', 'dispatched', 'delivered', 'cancelled']).optional(),
    preferredDeliveryDate: z.string().optional(),
    internalComments: z.string().optional(),
    orderPriority: z.enum(['low', 'medium', 'high']).optional(),
    salesChannel: z.enum(['online', 'phone', 'inPerson', 'agent']).optional(),
    crmSync: z.boolean().optional(),
    invoiceNumber: z.string().optional(),
  }).optional(),
  compliance: z.object({
    exportLicense: z.string().optional(),
    qualityCertification: z.enum(['iso22000', 'haccp', 'organic', 'none']).optional(),
    customsDeclaration: z.string().optional(),
    complianceNotes: z.string().optional(),
    digitalSignature: z.string().optional(),
  }).optional(),
  confirmation: z.object({
    confirmedBy: z.string().optional(),
    confirmationDate: z.string().optional(),
    confirmationStatus: z.enum(['pending', 'confirmed', 'rejected']).optional(),
  }).optional(),
  notes: z.object({
    internalNotes: z.string().optional(),
    clientNotes: z.string().optional(),
  }).optional(),
  attachments: z.object({
    attachment: z.array(z.any()).optional(),
    attachmentName: z.array(z.string()).optional(),
  }).optional(),
  status: z.enum(['draft', 'submitted', 'processing', 'completed', 'cancelled']).optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
  createdBy: z.string().optional(),
  updatedBy: z.string().optional(),
  clientId: z.string().optional(),
  dispatchDetails: z.array(z.any()).optional(),
  salesOpsDetails: z.array(z.any()).optional(),
  complianceDetails: z.array(z.any()).optional(),
  adminConfirmationDetails: z.array(z.any()).optional(),
});