import { FormData } from '../types/form';

export const initialFormData: FormData = {
  clientInfo: {
    fullName: '',
    phoneNumber: '',
    email: '',
    gender: undefined,
    address: '',
    clientCategory: 'Farmer',
    dateOfRegistration: new Date().toISOString().split('T')[0],
    referredBy: '',
    preferredContactMethod: 'SMS',
    businessName: '',
    taxId: '',
    loyaltyProgram: false,
    clientTier: 'Standard',
    accountManager: '',
    clientPhoto: null,
  },
  orderDetails: [
    {
      orderCategory: 'Retail',
      productName: 'Soy Oil',
      sku: `SOY-${Math.random().toString(36).slice(2, 7)}`,
      unitType: 'Liters',
      quantity: 1,
      unitPrice: 0,
      discount: 0,
      notes: '',
      orderUrgency: 'Standard',
      packagingPreference: undefined,
      paymentSchedule: undefined,
    },
  ],
  dispatch: [],
  salesOps: {
    salesRepresentative: '',
    paymentStatus: 'Pending',
    paymentMethod: undefined,
    paymentReceived: 0,
    paymentReceipt: null,
    deliveryStatus: 'Processing',
    preferredDeliveryDate: '',
    internalComments: '',
    orderPriority: 'Low',
    salesChannel: 'Online',
    crmSync: false,
    invoiceNumber: '',
  },
  compliance: {
    exportLicense: '',
    qualityCertification: undefined,
    customsDeclaration: '',
    complianceNotes: '',
    digitalSignature: '',
  },
  confirmation: {
    confirmedBy: '',
    confirmationDate: '',
    confirmationStatus: 'Pending',
  },
  notes: {
    internalNotes: '',
    clientNotes: '',
  },
  attachments: {
    attachment: [],
    attachmentName: [],
  },
  status: 'Draft',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  createdBy: 'User',
};