import { FormData } from '../types/form';
import { ClientInfo } from '../types/client';
import { OrderEntry } from '../types/order';
import { DispatchEntry } from '../types/dispatch';

export const initialFormData: FormData = {
clientInfo: {
    fullName: '',
    phoneNumber: '',
    email: '',
    gender: undefined,
    address: '',
    clientCategory: 'Individual Buyer',
    dateOfRegistration: new Date().toISOString().split('T')[0],
    referredBy: '',
    preferredContactMethod: 'SMS',
    businessName: '',
    taxId: '',
    loyaltyProgram: false,
    clientTier: 'Standard',
    accountManager: '',
    clientPhoto: undefined,
  } as ClientInfo,
  orderDetails: [{
    orderCategory: 'Retail',
    productName: 'Soy Oil',
    sku: `SOY-${Math.random().toString(36).slice(2, 7)}`,
    unitType: 'Liters',
    quantity: 1,
    unitPrice: 0,
    discount: 0,
    notes: '',
    orderUrgency: 'Standard',
    packagingPreference: 'Standard',
    paymentSchedule: 'Full Payment',
  }] as OrderEntry[],
  dispatch: [{
    dispatchDate: '',
    product: '',
    quantityDispatched: 1,
    transportMethod: 'Truck',
    trackingReference: '',
    dispatchNotes: '',
    driverContact: '',
    warehouseLocation: 'Kigali',
    dispatchStatus: 'Scheduled',
    blockchainHash: '',
  }] as DispatchEntry[],
  salesOps: {
    salesRepresentative: '',
    paymentStatus: 'Pending',
    paymentMethod: undefined,
    paymentReceived: undefined,
    paymentReceipt: undefined,
    deliveryStatus: 'Processing',
    preferredDeliveryDate: '',
    internalComments: '',
    orderPriority: 'Medium',
    salesChannel: 'Online',
    crmSync: false,
    invoiceNumber: '',
  },
  compliance: {
    exportLicense: '',
    qualityCertification: 'None',
    customsDeclaration: '',
    complianceNotes: '',
    digitalSignature: '',
  },
  confirmation: false,
};